from __future__ import annotations

import os
import re

from .. import agent_types
from ...media.media_taxonomy import MEDIA_ABSTRACT_CONCEPT_CUES, MEDIA_COLLECTION_CUES, MEDIA_INTENT_KEYWORDS, MEDIA_REGION_ALIASES, MEDIAWIKI_FILLER_PATTERNS
from ...planner.router_config import (
    ROUTER_CHAT_CUES,
    ROUTER_COLLECTION_NEGATIVE_CUES,
    ROUTER_CONFIDENCE_HIGH,
    ROUTER_CONFIDENCE_MEDIUM,
    ROUTER_MEDIA_DETAIL_CUES,
    ROUTER_MEDIA_SURFACE_CUES,
    ROUTER_REALTIME_CUES,
    ROUTER_RECENT_CUES,
    ROUTER_TECH_CUES,
)


CLASSIFIER_LABEL_MEDIA = agent_types.CLASSIFIER_LABEL_MEDIA
CLASSIFIER_LABEL_OTHER = agent_types.CLASSIFIER_LABEL_OTHER
CLASSIFIER_LABEL_TECH = agent_types.CLASSIFIER_LABEL_TECH
QUERY_TYPE_GENERAL = agent_types.QUERY_TYPE_GENERAL
QUERY_TYPE_MEDIA = agent_types.QUERY_TYPE_MEDIA
QUERY_TYPE_MIXED = agent_types.QUERY_TYPE_MIXED
QUERY_TYPE_TECH = agent_types.QUERY_TYPE_TECH
TOOL_EXPAND_MEDIAWIKI_CONCEPT = agent_types.TOOL_EXPAND_MEDIAWIKI_CONCEPT
TOOL_SEARCH_TMDB = agent_types.TOOL_SEARCH_TMDB
TOOL_SEARCH_WEB = agent_types.TOOL_SEARCH_WEB

SHORT_QUERY_MAX_TOKENS = 5
LONG_QUERY_MIN_TOKENS = int(os.getenv("NAV_DASHBOARD_LONG_QUERY_MIN_TOKENS", "12") or "12")
SHORT_QUERY_THRESHOLD_DELTA = float(os.getenv("NAV_DASHBOARD_SHORT_QUERY_THRESHOLD_DELTA", "-0.08") or "-0.08")
LONG_QUERY_THRESHOLD_DELTA = float(os.getenv("NAV_DASHBOARD_LONG_QUERY_THRESHOLD_DELTA", "0.08") or "0.08")
SHORT_QUERY_VECTOR_TOP_N_DELTA = int(os.getenv("NAV_DASHBOARD_SHORT_QUERY_VECTOR_TOP_N_DELTA", "6") or "6")
LONG_QUERY_VECTOR_TOP_N_DELTA = int(os.getenv("NAV_DASHBOARD_LONG_QUERY_VECTOR_TOP_N_DELTA", "-4") or "-4")
SHORT_QUERY_TOP_K_DELTA = int(os.getenv("NAV_DASHBOARD_SHORT_QUERY_TOP_K_DELTA", "2") or "2")
LONG_QUERY_TOP_K_DELTA = int(os.getenv("NAV_DASHBOARD_LONG_QUERY_TOP_K_DELTA", "-1") or "-1")
DOC_VECTOR_TOP_N = int(os.getenv("NAV_DASHBOARD_DOC_VECTOR_TOP_N", "12") or "12")
TECH_QUERY_DOC_SIM_THRESHOLD = float(os.getenv("NAV_DASHBOARD_TECH_QUERY_DOC_SIM_THRESHOLD", "0.3") or "0.3")
ALLOWED_RANKING_MODES: frozenset[str] = frozenset({"relevance", "rating_desc", "rating_asc", "newest", "oldest"})

MEDIA_TITLE_MARKER_RE = re.compile(r"《[^》]+》")


__all__ = [name for name in globals() if name.isupper()]